export const BASE_API = import.meta.env.VITE_APP_SERVER_URL + "api/";
export const DERIVATIVE_API = import.meta.env.VITE_DERIVATIVE_URL;
export const MARKET_CHAIN = import.meta.env.VITE_MARKET_CHAIN;
export const MARKET_CHAIN_ID = parseInt(import.meta.env.VITE_MARKET_CHAIN_ID);
export const CRYPTOCOMPARE_API_KEY = import.meta.env.VITE_CRYPTOCOMPARE_API_KEY;
export const NULL_ADDRESS = "0x0000000000000000000000000000000000000000";
export const INFURA_ID = import.meta.env.VITE_INFURA_ID;

export const COMPANY_ADDRESS =
  import.meta.env.VITE_COMPANY_ADDRESS.toLowerCase();
export const BSC_TESTNET_VBNB_ADDRESS =
  import.meta.env.VITE_BSC_TESTNET_VBNB_ADDRESS.toLowerCase();

export const BSC_TESTNET_SOCIAL_NFT_CONTRACT_ADDRESS =
  import.meta.env.VITE_BSC_TESTNET_SOCIAL_NFT_CONTRACT_ADDRESS.toLowerCase();

export const BSC_TESTNET_MARKET_CONTRACT_ADDRESS =
  import.meta.env.VITE_BSC_TESTNET_MARKET_CONTRACT_ADDRESS.toLowerCase();
export const BSC_TESTNET_MARKET_FARMING_CONTRACT_ADDRESS =
  import.meta.env.VITE_BSC_TESTNET_MARKET_FARMING_CONTRACT_ADDRESS.toLowerCase();
export const BSC_TESTNET_MARKET_ORDER_CONTRACT_ADDRESS =
  import.meta.env.VITE_BSC_TESTNET_MARKET_ORDER_CONTRACT_ADDRESS.toLowerCase();
export const BSC_TESTNET_MARKET_OFFER_CONTRACT_ADDRESS =
  import.meta.env.VITE_BSC_TESTNET_MARKET_OFFER_CONTRACT_ADDRESS.toLowerCase();

export const BSC_TESTNET_MLR_MANAGE_CONTRACT_ADDRESS =
  import.meta.env.VITE_BSC_TESTNET_MLR_MANAGE_CONTRACT_ADDRESS.toLowerCase();
export const BSC_TESTNET_MLR_FACTORY_CONTRACT_ADDRESS =
  import.meta.env.VITE_BSC_TESTNET_MLR_FACTORY_CONTRACT_ADDRESS.toLowerCase();
export const BSC_TESTNET_MLR_ORDER_FACTORY_CONTRACT_ADDRESS =
  import.meta.env.VITE_BSC_TESTNET_MLR_ORDER_FACTORY_CONTRACT_ADDRESS.toLowerCase();
export const BSC_TESTNET_MLR_OFFER_FACTORY_CONTRACT_ADDRESS =
  import.meta.env.VITE_BSC_TESTNET_MLR_OFFER_FACTORY_CONTRACT_ADDRESS.toLowerCase();
export const BSC_TESTNET_MLR_FARMING_CONTRACT_ADDRESS =
  import.meta.env.VITE_BSC_TESTNET_MLR_FARMING_CONTRACT_ADDRESS.toLowerCase();

export const BSC_TESTNET_VAULT_CONTRACT_ADDRESS =
  import.meta.env.VITE_BSC_TESTNET_VAULT_CONTRACT_ADDRESS.toLowerCase();

export const BSC_TESTNET_PACKABLE_CONTRACT_ADDRESS =
  import.meta.env.VITE_BSC_TESTNET_PACKABLE_CONTRACT_ADDRESS.toLowerCase();
export const BSC_TESTNET_DVC_FACTORY_CONTRACT_ADDRESS =
  import.meta.env.VITE_BSC_TESTNET_DVC_FACTORY_CONTRACT_ADDRESS.toLowerCase();
export const BSC_TESTNET_SYNDICATION_MARKET_FACTORY_CONTRACT_ADDRESS =
  import.meta.env.VITE_BSC_TESTNET_SYNDICATION_MARKET_FACTORY_CONTRACT_ADDRESS.toLowerCase();
export const BSC_TESTNET_SYNDICATION_MLR_FACTORY_CONTRACT_ADDRESS =
  import.meta.env.VITE_BSC_TESTNET_SYNDICATION_MLR_FACTORY_CONTRACT_ADDRESS.toLowerCase();
export const BSC_TESTNET_DERIVATIVE_FACTORY_CONTRACT_ADDRESS =
  import.meta.env.VITE_BSC_TESTNET_DERIVATIVE_FACTORY_CONTRACT_ADDRESS.toLowerCase();

export const BSC_TESTNET_PUBLIC_SALE_CONTRACT_ADDRESS =
  import.meta.env.VITE_BSC_TESTNET_PUBLIC_SALE_CONTRACT_ADDRESS.toLowerCase();
